version: '3.8'
services:
  backend:
    build: ./server
    ports:
      - '3000:3000'
    environment:
      DB_HOST: localhost
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: my_db
  frontend:
    build: ./client
    ports:
      - '8080:80'
